import cocotb
from cocotb.triggers import FallingEdge


class ALUDriver:
    def __init__(self, dut, gen_queue):
        self.dut = dut
        self.gen_queue = gen_queue

        # Initialize inputs at time 0
        self.dut.rst_n.value = 0
        self.dut.a.value = 0
        self.dut.b.value = 0
        self.dut.op.value = 0

    async def run(self):
        while True:
            # Pull transaction generated by the ALUGenerator
            tr = await self.gen_queue.get()

            # Drive inputs on the FALLING edge so they are stable
            # for the DUT's next rising edge
            await FallingEdge(self.dut.clk)

            try:
                self.dut.rst_n.value = int(tr.rst_n)
                self.dut.a.value = int(tr.a)
                self.dut.b.value = int(tr.b)
                self.dut.op.value = int(tr.op)
            except (ValueError, TypeError):
                cocotb.log.error(
                    f"Driver: Received invalid transaction data: {tr}")
                self.dut.rst_n.value = 1
                self.dut.a.value = 0
                self.dut.b.value = 0
                self.dut.op.value = 0
