# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vlog -work work +define+COCOTB_SIM -sv -timescale 1ns/1ps -mfcu +acc  C:/python_test/EX4/simple_dut.sv
vsim  -onfinish stop -pli C:/Users/Moustafa/miniconda3/Lib/site-packages/cocotb/libs/cocotbvpi_modelsim.dll   sim_build/work.simple_dut
log -recursive /*
add log -r *
