// Analog Devices 
// GP Ain-shams University
// Twiddle Rom for 4096-FFT 


/* Description ..........
   Twiddle rom store the values of the twiddle factors W_N^k = e^(-j*2*pi*k/N) for k = 0 to N/2-1, where N is the FFT size (4096 in this case).
   since for each stage we need N/2 twiddle factors only to be stored in the rom and the rest can be generated by symmetry, 
   for stage 12 we store 2048 twiddle factors and for stage 11 we store 1024 and so on ...

   The values are generated using MATLAB script and stored in a text file like this "8000 real then 7FFC img", 
   then we read the values from the text file and store them in the ROM.
*/

module twiddle_rom #(
    parameter WL = 16,
    parameter DEPTH = 2048, // Half-wave or whatever your ROM depth is
    parameter FILE_REAL = "twiddlerom/twiddle_stage_12_real.mem",
    parameter FILE_IMAG = "twiddlerom/twiddle_stage_12_imag.mem"
)(

    // --- PORT A: Dedicated to the FFT ---
    input  wire [(DEPTH == 1) ? 0 : $clog2(DEPTH)-1 : 0] addr_a,
    output reg  signed [WL-1:0]   tw_re_a,
    output reg  signed [WL-1:0]   tw_im_a,

    // --- PORT B: Dedicated to the IFFT ---
    input  wire [(DEPTH == 1) ? 0 : $clog2(DEPTH)-1 : 0] addr_b,
    output reg  signed [WL-1:0]   tw_re_b,
    output reg  signed [WL-1:0]   tw_im_b
);

    // The physical memory arrays
    reg signed [WL-1:0] twiddle_rom_real [0:DEPTH-1];
    reg signed [WL-1:0] twiddle_rom_img  [0:DEPTH-1];

    // Load the Q2.14 values at compilation
    initial begin
        $readmemh(FILE_REAL, twiddle_rom_real);
        $readmemh(FILE_IMAG, twiddle_rom_img);
    end

    // Port A Read (FFT)
    always @(*) begin
        tw_re_a =  twiddle_rom_real [addr_a];
        tw_im_a =  twiddle_rom_img  [addr_a];
    end

    // Port B Read (IFFT)
    always @(*) begin
        tw_re_b =  twiddle_rom_real [addr_b];
        tw_im_b = -twiddle_rom_img  [addr_b]; // For IFFT, we take the complex conjugate of the twiddle factors,
                                             // which means negating the imaginary part
    end

endmodule