# ==============================================================================
# Execution Shortcuts for FFT Testcases (runs.mk)
# ==============================================================================

run_impulse:
	make -f Makefile TESTCASE=test_fft_impulse

run_random:
	make -f Makefile TESTCASE=test_fft_random

run_ofdm:
	make -f Makefile TESTCASE=test_fft_ofdm_qam

run_ranging:
	make -f Makefile TESTCASE=test_fft_ranging_pilots

run_ten:
	make -f Makefile TESTCASE=test_fft_ten_samples

run_latency:
	make -f Makefile TESTCASE=test_fft_latency

run_zero:
	make -f Makefile TESTCASE=test_fft_zero

run_random:
	make -f Makefile TESTCASE=test_fft_random



run_all:
	make -f Makefile