// Analog Devices 
// GP Ain-shams University
// Twiddle Rom for 4096-FFT 


/* Description ..........
   Twiddle rom store the values of the twiddle factors W_N^k = e^(-j*2*pi*k/N) for k = 0 to N/2-1, where N is the FFT size (4096 in this case).
   since for each stage we need N/2 twiddle factors only to be stored in the rom and the rest can be generated by symmetry, 
   for stage 12 we store 2048 twiddle factors and for stage 11 we store 1024 and so on ...

   The values are generated using MATLAB script and stored in a text file like this "8000 real then 7FFC img", 
   then we read the values from the text file and store them in the ROM.
*/


module twiddlerom #(
    parameter DEPTH=2048, // Number of twiddle factors to store (N/2 for stage 12) .. will be passed from the top-level module for each stage
    parameter WL=16,
    parameter FILE_REAL="twiddlerom/twiddle_stage_12_real.mem",
    parameter FILE_IMAG="twiddlerom/twiddle_stage_12_imag.mem"
) (
    input wire [(DEPTH == 1) ? 0 : $clog2(DEPTH)-1 : 0] addr, // Address input to select the twiddle factor
    output reg signed [WL-1:0] W_real, // Real part of the twiddle factor
    output reg signed [WL-1:0] W_img // Imaginary part of the twiddle factor 
);
    // ROM to store the twiddle factors

    reg signed [WL-1:0] twiddle_rom_real [0:DEPTH-1];  // real part of the twiddle factors
    reg signed [WL-1:0] twiddle_rom_img  [0:DEPTH-1];  // imaginary part of the twiddle factors


    // Initialize the ROM with the twiddle factors 
    initial begin
        $readmemh(FILE_REAL, twiddle_rom_real);
        $readmemh(FILE_IMAG, twiddle_rom_img);
    end


    always @(*) begin
        W_real = twiddle_rom_real[addr]; // Output the selected real part
        W_img = twiddle_rom_img[addr]; // Output the selected imaginary part
    end

endmodule