# ==============================================================================
# Execution Shortcuts for FFT & RX Testcases
# ==============================================================================

# ------------------------------------------------------------------------------
# TX / FFT BLOCK TESTS (Legacy)
# ------------------------------------------------------------------------------
run_zero_ref:
	make -f Makefile MODULE=zero_ref_chirp_test TESTCASE=zero_ref_chirp_test

run_inputknowm:
	make -f Makefile MODULE=rtl_hex_chirp_test TESTCASE=rtl_hex_chirp_test

run_inputtxt:
	make MODULE=rtl_txt_chirp_test TESTCASE=rtl_txt_chirp_test


run_inputmixed:
	make -f Makefile MODULE=mixed_ofdm_radar_test TESTCASE=mixed_ofdm_radar_test	


run_inputmixed_no_quant:
	make -f Makefile MODULE=mixed_ofdm_radar_float_test TESTCASE=mixed_ofdm_radar_test

run_inputsmall:
	make -f Makefile MODULE=mixed_ofdm_radar_small_test TESTCASE=mixed_ofdm_radar_small_test


run_optimal:
	make MODULE=mixed_ofdm_radar_optimal_test TESTCASE=mixed_ofdm_radar_optimal_test











