"""
    Sponsor: Analog Devices, Inc. (ADI)
    Institution: Faculty of Engineering, Ain Shams University
    Project: DDS for 5G/6G Cellular Network Calibration and Ranging

    Module: tc_rx_002_zero_ref_chirp_seq.py

    Description:
        TC-RX-002: Zero Reference, Chirp Signal In.
        Feature: F-RX-02

    STIMULUS:
        Apply a chirp-only signal (energy placed in the radar bins only)
        to rx_in for one full 4096-sample frame.
        Reference RAM is never written → all locations remain 0.
        Capture radar_valid_out and ofdm_valid_out.

    EXPECTED / PASS:
        radar_out = 0  (multiply by zero reference → output is zero).
        ofdm_out   matches the golden FFT model (zeros in OFDM bins
        because the chirp energy is placed only in radar bins 2048-4095).

    Sequence structure  (mirrors output_word_format_seq.py style)
    ──────────────────────────────────────────────────────────────
    Phase 0 — Reset
        Assert rst_n=0 for RESET_CYCLES clock periods.

    Phase 1 — No reference write
        Reference RAM is deliberately never written (ref_wr_en stays 0),
        so all 2048 locations read back as zero.

    Phase 2 — Chirp rx_in frame  (4096 cycles)
        Drive rx_valid_in=1 with the chirp time-domain samples.
        Chirp is generated by:
            1. Build a 4096-bin frequency frame with zeros in OFDM bins
               (0-2047) and a linear-phase radar chirp in bins 2048-4095.
            2. IFFT to time domain → 16-bit signed fixed-point (Q8.8).

    Phase 3 — Pipeline drain  (DRAIN_CYCLES idle cycles)
        rx_valid_in=0, ref_wr_en=0.  Allows all pipeline stages
        (FFT + 2×bit_rev + IFFT) to flush and produce their outputs.
"""

import numpy as np
import cocotb
import logging
from pyuvm import *
from top_seq_item import *
import pyuvm
import cocotb
from cocotb.triggers import *

# ─────────────────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────────────────
WL           = 16
FL           = 8          # Q8.8 fixed-point
N_FFT        = 4096
N_HALF       = 2048
MAX_VAL      =  (1 << (WL - 1)) - 1   #  32767
MIN_VAL      = -(1 << (WL - 1))       # -32768
RESET_CYCLES = 8
# Conservative drain: FFT(4096) + bit_rev + IFFT(2048) + bit_rev + margins
#DRAIN_CYCLES = N_FFT + N_HALF * 3 + 256
DRAIN_CYCLES = 16000   # generous drain to ensure all outputs are captured

# ─────────────────────────────────────────────────────────────────────────────
# Helper — float → signed Q8.8 integer, saturated
# ─────────────────────────────────────────────────────────────────────────────
def _f2q(f: float) -> int:
    return max(MIN_VAL, min(MAX_VAL, int(round(f * (1 << FL)))))


# ─────────────────────────────────────────────────────────────────────────────
# Helper — build chirp time-domain frame
# ─────────────────────────────────────────────────────────────────────────────
def _build_chirp_rx_frame() -> list:
    """
    Build a 4096-sample time-domain rx_in frame that places chirp energy
    exclusively in the radar bins (2048-4095) of the 4096-bin FFT.

    Method:
        1. Construct a 4096-bin frequency frame:
               bins  0   .. 2047 = 0  (OFDM region → zero)
               bins 2048 .. 4095 = complex chirp spectrum (linear phase sweep)
        2. Take the IFFT to produce the time-domain stimulus.
        3. Quantize to signed 16-bit Q8.8.

    Returns:
        list of (re_int, im_int) pairs — 4096 samples.
    """
    freq_frame = np.zeros(N_FFT, dtype=np.complex128)

    # Linear-phase chirp across radar bins 2048..4095 (1667 active bins)
    # Phase increments linearly: φ[k] = π * k² / N_HALF
    # Amplitude scaled to half full-scale to avoid saturation after IFFT
    radar_amp   = MAX_VAL / 8.0    # conservative amplitude
    for k in range(N_HALF, N_FFT):
        k_local          = k - N_HALF
        phase            = np.pi * k_local * k_local / N_HALF
        freq_frame[k]    = radar_amp * np.exp(1j * phase)

    # IFFT → time domain  (scale by N_FFT to match hardware convention)
    td = np.fft.ifft(freq_frame) * N_FFT

    return [(_f2q(float(s.real)), _f2q(float(s.imag))) for s in td]


# ─────────────────────────────────────────────────────────────────────────────
# Helper — send one rx_item
# ─────────────────────────────────────────────────────────────────────────────
async def _send(seq, name,
                rst_n    = 1,
                rx_valid = 0, rx_re = 0, rx_im = 0,
                ref_wr   = 0, ref_re = 0, ref_im = 0):
    req = rx_item.create(name)
    await seq.start_item(req)
    req.rst_n       = rst_n
    req.rx_valid_in = rx_valid
    req.rx_in_re    = rx_re
    req.rx_in_im    = rx_im
    req.ref_wr_en   = ref_wr
    req.ref_wr_re   = ref_re
    req.ref_wr_im   = ref_im
    await seq.finish_item(req)


# ─────────────────────────────────────────────────────────────────────────────
# TC-RX-002 sequence
# ─────────────────────────────────────────────────────────────────────────────
class zero_ref_chirp_seq(uvm_sequence):
    """
    TC-RX-002: Zero Reference, Chirp Signal In.
    Reference RAM is never written. A chirp signal with energy only in
    radar bins is driven into rx_in for one full 4096-sample frame.

    Attributes (configurable before start):
        num_frames  : int — how many frames to run (default 1)
    """

    def __init__(self, name="zero_ref_chirp_seq"):
        super().__init__(name)
        self.num_frames = 1

    async def body(self):

        # Pre-compute the chirp time-domain frame once
        chirp_samples = _build_chirp_rx_frame()  # list of (re, im)

        for frame_idx in range(self.num_frames):

            cocotb.log.info(
                f"TC-RX-002 frame {frame_idx + 1}/{self.num_frames}: "
                f"starting — Zero reference, chirp signal in."
            )

            # ══════════════════════════════════════════════════════════
            # PHASE 0: Reset
            # Assert rst_n=0 for RESET_CYCLES, then release.
            # ══════════════════════════════════════════════════════════
            for cyc in range(RESET_CYCLES):
                await _send(self, f"rst_{frame_idx}_{cyc}", rst_n=0)

            # One idle cycle with reset released
            await _send(self, f"rst_release_{frame_idx}", rst_n=1)

            cocotb.log.info(
                f"TC-RX-002 frame {frame_idx + 1}: reset complete."
            )

            # ══════════════════════════════════════════════════════════
            # PHASE 1: Reference RAM — deliberately NOT written.
            # Reference stays at zero (power-on reset value).
            # No ref_wr_en pulses are driven here.
            # ══════════════════════════════════════════════════════════
            cocotb.log.info(
                f"TC-RX-002 frame {frame_idx + 1}: "
                f"reference RAM skipped (stays zero) — "
                f"multiplier output will be forced to zero."
            )

            # ══════════════════════════════════════════════════════════
            # PHASE 2: Drive chirp rx_in frame (4096 samples)
            # rx_valid_in=1, ref_wr_en=0.
            # The chirp has energy only in radar FFT bins 2048-4095.
            # OFDM bins 0-2047 will be zero after the demux.
            # ══════════════════════════════════════════════════════════
            cocotb.log.info(
                f"TC-RX-002 frame {frame_idx + 1}: "
                f"driving {N_FFT} chirp samples (rx_valid_in=1)..."
            )

            for cycle in range(N_FFT):
                re, im = chirp_samples[cycle]
                await _send(
                    self,
                    f"chirp_{frame_idx}_{cycle}",
                    rst_n    = 1,
                    rx_valid = 1,
                    rx_re    = re,
                    rx_im    = im,
                    ref_wr   = 0,
                )

            # De-assert rx_valid_in at end of frame
            await _send(self, f"chirp_done_{frame_idx}", rst_n=1)

            cocotb.log.info(
                f"TC-RX-002 frame {frame_idx + 1}: "
                f"chirp frame complete. Entering drain phase..."
            )

            # ══════════════════════════════════════════════════════════
            # PHASE 3: Pipeline drain
            # All inputs idle. Wait for both ofdm_valid_out and
            # radar_valid_out to fully arrive from the pipeline.
            # ══════════════════════════════════════════════════════════
            for cyc in range(DRAIN_CYCLES):
                await _send(self, f"drain_{frame_idx}_{cyc}", rst_n=1)

            cocotb.log.info(
                f"TC-RX-002 frame {frame_idx + 1}: "
                f"drain complete — frame done."
            )